### ISSUE TITLE
🛣️ Roadmap for LieGroups.jl

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/LieGroups.jl#1]
# 🛣️ Roadmap for LieGroups.jl

* [ ] Everyine who wants to be initial contributor, consider to add your name to the `Project.toml`, `LICENSE`, the `authors=` field in the `docs/make.jl`, and the `.zenodo.json` (@mateuszbaran, @olivierverdier ...?)
* [ ] Discuss how to handle different `exp`s (maybe a `ExponentialType` parameter simimlar to retracitons?)
* [ ] Discuss whether it is useful to have a `LieGroupPoint` and a `LieAlgebraVector` type (optional, like in Manifolds?)
* [ ] Advantage of these types would we, that we can introduce a `⋅` operator for group actions
* List of functions to “move to” (first define in ) this package
  * (fill be filled soon)
* List of Lie Groups to move here
  * (will be filled soon)
* [ ] write a generic Lie group test suite (@kellertuer)
* [ ] Discuss name and check with the maybe inactive package https://github.com/yuehhua/LieGroups.jl
* [ ] Write a “Get started” tutorial

Further ideas both in form on further issues (I will link here) as well as comments are are welcome.
Let's first collect the ideas before we get started.

**Comment by dev10110** [comment]
This is awesome! Thanks Ronny!

**Comment by mateuszbaran** [comment]
Nice list! I think we should also move group actions here.

**Comment by kellertuer** [comment]
Well-spotted, sure they should move as well.

I will try to find time to write down a few design remarks and introduce the first main types maybe until or over the weekend. and then we could try to slowly move some parts

**Comment by kellertuer** [comment]
There might be a few small hiccups from now, since we are taking over the old LieGroups.jl and rebase this.
